using System.Windows.Input;

namespace Horizon.Utilities;

/// <summary>
/// Contains constants for handling key codes.
/// </summary>
public static class KeyConstants
{
    /// <summary>
    /// Contains a list of keys that should be rendered as medium size.
    /// </summary>
    public static List<Key> MediumSizeKeys { get; } =
    [
        Key.Tab,
        Key.CapsLock,
        Key.LeftShift,
        Key.RightShift,
        Key.LeftAlt,
        Key.RightAlt,
        Key.LeftCtrl,
        Key.RightCtrl,
        Key.Back,
        Key.Apps,
        Key.Enter,
        Key.Add,
        Key.Insert
    ];

    /// <summary>
    /// Contains the friendly names for each defined key on the keyboard.
    /// </summary>
    public static Dictionary<Key, string> KeyNames { get; } = new()
    {
        [Key.Escape] = "Esc",
        [Key.F1] = "F1",
        [Key.F2] = "F2",
        [Key.F3] = "F3",
        [Key.F4] = "F4",
        [Key.F5] = "F5",
        [Key.F6] = "F6",
        [Key.F7] = "F7",
        [Key.F8] = "F8",
        [Key.F9] = "F9",
        [Key.F10] = "F10",
        [Key.F11] = "F11",
        [Key.F12] = "F12",
        [Key.PrintScreen] = "Print Sc",
        [Key.Scroll] = "Scroll Lock",
        [Key.Pause] = "Pause",
        [Key.Oem3] = "`",
        [Key.D1] = "1",
        [Key.D2] = "2",
        [Key.D3] = "3",
        [Key.D4] = "4",
        [Key.D5] = "5",
        [Key.D6] = "6",
        [Key.D7] = "7",
        [Key.D8] = "8",
        [Key.D9] = "9",
        [Key.D0] = "0",
        [Key.OemMinus] = "-",
        [Key.OemPlus] = "+",
        [Key.Back] = "Backspace",
        [Key.Tab] = "Tab",
        [Key.Q] = "Q",
        [Key.W] = "W",
        [Key.E] = "E",
        [Key.R] = "R",
        [Key.T] = "T",
        [Key.Y] = "Y",
        [Key.U] = "U",
        [Key.I] = "I",
        [Key.O] = "O",
        [Key.P] = "P",
        [Key.Oem4] = "[",
        [Key.Oem6] = "]",
        [Key.Oem5] = "\\",
        [Key.CapsLock] = "Caps Lock",
        [Key.A] = "A",
        [Key.S] = "S",
        [Key.D] = "D",
        [Key.F] = "F",
        [Key.G] = "G",
        [Key.H] = "H",
        [Key.J] = "J",
        [Key.K] = "K",
        [Key.L] = "L",
        [Key.Oem1] = ";",
        [Key.Oem7] = "'",
        [Key.Enter] = "Enter",
        [Key.LeftShift] = "Shift",
        [Key.Z] = "Z",
        [Key.X] = "X",
        [Key.C] = "C",
        [Key.V] = "V",
        [Key.B] = "B",
        [Key.N] = "N",
        [Key.M] = "M",
        [Key.OemComma] = ",",
        [Key.OemPeriod] = ".",
        [Key.Oem2] = "/",
        [Key.RightShift] = "Shift",
        [Key.LeftCtrl] = "Ctrl",
        [Key.LWin] = "Win",
        [Key.LeftAlt] = "Alt",
        [Key.Space] = "Space",
        [Key.RightAlt] = "Alt",
        [Key.Apps] = "≣",
        [Key.RightCtrl] = "Ctrl",
        [Key.Insert] = "Insert",
        [Key.Home] = "Home",
        [Key.PageUp] = "Pg Up",
        [Key.Delete] = "Delete",
        [Key.End] = "End",
        [Key.PageDown] = "Pg Dn",
        [Key.Up] = "↑",
        [Key.Down] = "↓",
        [Key.Left] = "←",
        [Key.Right] = "→",
        [Key.NumLock] = "Num Lock",
        [Key.Divide] = "Numpad /",
        [Key.Multiply] = "Numpad *",
        [Key.Subtract] = "Numpad -",
        [Key.Add] = "Numpad +",
        [Key.Decimal] = "Numpad .",
        [Key.NumPad1] = "N1",
        [Key.NumPad2] = "N2",
        [Key.NumPad3] = "N3",
        [Key.NumPad4] = "N4",
        [Key.NumPad5] = "N5",
        [Key.NumPad6] = "N6",
        [Key.NumPad7] = "N7",
        [Key.NumPad8] = "N8",
        [Key.NumPad9] = "N9",
        [Key.NumPad0] = "N0"
    };
}